{% set name = "crispy-bootstrap5" %}
{% set version = "2024.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crispy_bootstrap5-{{ version }}.tar.gz
  sha256: 55b442fe675dd95ad280123c7fe464f454186e90b8e5642e751f436c87627c44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >61
  run:
    - python >={{ python_min }}
    - django-crispy-forms >=2.3.0
    - django >=4.2

test:
  imports:
    - crispy_bootstrap5
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/django-crispy-forms/crispy-bootstrap5
  summary: Bootstrap5 template pack for django-crispy-forms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
