{% set name = "crispy-bootstrap5" %}
{% set version = "2024.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 55b442fe675dd95ad280123c7fe464f454186e90b8e5642e751f436c87627c44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django-crispy-forms >=1.13.0
    - django >=3.2

test:
  imports:
    - crispy_bootstrap5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-crispy-forms/crispy-bootstrap5
  summary: Bootstrap5 template pack for django-crispy-forms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
