{% set name = "crispy-bootstrap5" %}
{% set version = "2024.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crispy-bootstrap5-{{ version }}.tar.gz
  sha256: 7d1fa40c6faf472e30e85c72551a3d2c9eedbf0abfff920683315e4e6f670f2b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django-crispy-forms >=1.13.0
    - django >=3.2

test:
  imports:
    - crispy_bootstrap5
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-crispy-forms/crispy-bootstrap5
  summary: Bootstrap5 template pack for django-crispy-forms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
